### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by shayki5** [damienbod/AspNetCoreAngularSignalR#2]
Hi,
When I build, the command line is running, the browser opening but nothing, on Edge i get 403.

**Comment by PankajLala** [comment]
Using VS2017, solution compiles successfully. Debugging starts the application on port 5000, however page is blank

**Comment by damienbod** [comment]
@PankajLala @shayki5 The 3 apps use the different launch.settings which are configured for running in the IIS with HTTPS. 

The UI app also needs to be built, try from the cmd first from the project folder:

> npm install
> npm run build-dev

If this works, install te npm Task runner in VS and use the latest nodejs

The npm task runner should build the UI project.

What warning does the browser display? (F12)
Greetimgs Damien

**Comment by damienbod** [comment]
@PankajLala @shayki5 
tested this with a different user, PC. seems ok. I'll close this. Please re-open it, if you still have problems

Greetings Damien
