### ISSUE TITLE
In the demo it says @angular/platform-server unavailable 

### ISSUE THREAD

**Issue by access-pro** [damienbod/AspNetCoreAngularSignalR#3]
In VS2017 package.json it says @angular/platform-server unavailable.

**Comment by damienbod** [comment]
I don't have this problem. Could you try again?

> npm install
> npm run build-dev
> dotnet restore

Greetings Damien

**Comment by JulCesWhat** [comment]
You should probably add the commands in readme to get it running. It works great by the way.
