### ISSUE TITLE
Error in HubConnection 

### ISSUE THREAD

**Issue by alejandrovillaseca** [damienbod/AspNetCoreAngularSignalR#5]
Issue in Angular 6, with @aspnet/signalr instead @aspnet/signalr-client:

![image](https://user-images.githubusercontent.com/39783011/40851435-6a3157f0-6595-11e8-9699-d198e95c6c76.png)

**Comment by damienbod** [comment]
Hi @alesendoh 
yes, this has been changed, here's an example:

https://github.com/damienbod/AspNetCoreAngularSignalR/blob/master/src/AspNetCoreAngularSignalR/angularApp/app/home/components/home.component.ts#L29

Greetings Damien
