### ISSUE TITLE
Hi Damo - Have you figured out how to wire up ngrx / signalR with identityserver store?

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/AspNetCoreAngularSignalR#6]
Have you figured out how to wire up ngrx / signalR with identityserver store?

I thought I might pop on over to your repos incase you had worked it out and implemented it. I cant see if you have, so just asking if you have figured out how to do this.?

FYI, Im in the process of implementing a NX project where Im using Ionic and Angular 5 app to share a common auth lib using ngrx and hooking up to identityserver.

The whole signal R thing is obviously not required where auth is involved, but Im wondering for general crud how ngrx and signalR would be used and how identityserver could be used to protect the hub endpoints ( if that makes any sense? ), you can tell I have not done enough research on signalR at this stage. Anyways, If you have time, would love to hear your thoughts on this

Cheers

Nigel D.

**Comment by damienbod** [comment]
Hi @nigel-dewar 

Here's an example

https://github.com/damienbod/AspNetCoreAngularSignalRSecurity

greetings Damien

**Comment by nigel-dewar** [comment]
NICEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE!!!! Damo this is awesome!!

cheers mate, this is really good. Exactly what I was looking for. thanks a million mate.

Hopefully the day comes when I can share something useful back to yourself in return.
